### ISSUE TITLE
Alt not working if URL is not correct

### ISSUE THREAD

**Issue by MTLS-prog** [SavonAutomaatio/TwinCAT-HMI-Browser#1]
In settings if url address is not correct, browser chrash and alt keybord not work, in this case is not possible to adjust settings and is not usable anymore

**Comment by jessenic** [comment]
Thanks for the bug report, this is fixed now in https://github.com/SavonAutomaatio/TwinCAT-HMI-Browser/releases/tag/v1.0.5
